### PR TITLE
Update Heroicons to 2.1.1 and update dependency versions

### PR DESCRIPTION
**Pull request by stefanchrobot**
👋 Trying to update `phoenix_html` in my project to latest version fails because of the clash with `ex_heroicons`. This PR updates the dependencies to the latest versions. Latest `surface` still depends on `phoenix_html` 3.x though.

- Upgrade Heroicons to 2.1.1
- Update dependencies to support `phoenix_html` >= 4.0

### CODE REVIEW

**Comment by zpeters** [comment]
Has there been any movement here or any way i can pitch in? I'd love to see this PR come through for something I am working on

**Comment by bmelton** [comment]
Not getting this is in appears to be blocking things like phoenix_html 4.0 

Any way I can assist to get it in?

**Comment by sgerrand** [comment]
👋 @miguel-s, are you able to review this change? Are we able to assist in any way to get this merged?

**Comment by miguel-s** [comment]
Hi everyone! Sorry for the long silance and thank you for your contribution and comments

I just published version 3.0.0-rc.0 to Hex, please have a look :)

It ended up being a fairly big refactor now that Phoenix uses heex by default and Surface plays nicely with LV functional components. Here's a small migration guide https://github.com/miguel-s/ex_heroicons/blob/v3.0.0/CHANGELOG.md

**Comment by zpeters** [comment]
@miguel-s I have to send you a huge "thank you" for this.  I  haven't looked very deeply in the code, but I'm assuming with the version jump and what you've stated here this was a lot of work!  Your effort is appreciated!

**Pull request closed without merging**
